---
title: "VÁLASZTÁS 2022 - Hány százalékban értenek egyet a pártok bizonyos kérdésekben?"
output:
  flexdashboard::flex_dashboard:
    theme: united 
    orientation: rows
    vertical_layout: scroll
---

<style>                     
.navbar {
  background-color:black;
  border-color:black;
}


</style>   

```{r setup, include=FALSE}
library(flexdashboard)
source('voks.R') 
```
  
> A vokskabin.hu összegyűjtötte a pártok álláspontját 40 fontos kérdés mentén. Az alábbi vizualizáció azt mutatja be témákra bontva, hogy milyen arányban van egyetértés közöttük.
  
row {data-height=400}
-----------------------------------------------------------------------

### All {.no-padding .no-title}

```{r}
nw[[1]]
```

row {data-height=250, .no-padding}
-----------------------------------------------------------------------

### 2 {.no-title}

```{r}
nw[[2]]
```

### 3 {.no-title}

```{r}
nw[[3]]
```

### 4 {.no-title}

```{r}
nw[[4]]
```

### 5 {.no-title}

```{r}
nw[[5]]
```

### 6 {.no-title}

```{r}
nw[[6]]
```

### 7 {.no-title}

```{r}
nw[[7]]
```


row {data-height=250, .no-padding}
-----------------------------------------------------------------------

### 8 {.no-title }  

```{r}
nw[[8]]
```

### 9 {.no-title }

```{r}
nw[[9]]
```

### 10 {.no-title }

```{r}
nw[[10]]
```


### 11 {.no-title }

```{r}
nw[[11]]
```

### 12 {.no-title}

```{r}
nw[[12]]
```

### 13 {.no-title} 

```{r}
nw[[13]]
```

row {data-height=50, .no-padding}
-----------------------------------------------------------------------

> Az adatok forrása a vokskabin.hu

